### ISSUE TITLE
Class Nameing

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [simpleauthority/proxychannels#2]
I would recommend changeing your  main class'es name. It being "Main" can cause issues with other plugins.

**Comment by simpleauthority** [comment]
The class is namespaced by the package; it cannot interfere with another plugin due to the class's name.
For now, I disagree with this issue.

**Comment by xXXIMMATTHEWXXx** [comment]
Even then, naming the primary class main is not recommend and really does not describe what the class does.

**Comment by simpleauthority** [comment]
Will rename to "ScbPlugin.java" in next release.

**Comment by xXXIMMATTHEWXXx** [comment]
If you so wish I can make a pr for you

**Comment by simpleauthority** [comment]
If you'd like to do that, you may. Thanks!
