### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by AllenCC** [simpleauthority/proxychannels#3]
You cannot open website links that are posted in the chat

**Comment by simpleauthority** [comment]
I will look into this. What version of Minecraft and Bungee are you running? Does hovering the components work?

Any extra information?

**Comment by AllenCC** [comment]
The hoovering components do work. 
I have tried it on waterfall #103 and bungeecord #1228 on minecraft versions 1.8.8 and 1.11.2 using the default staffchatbungee configuration.

**Comment by simpleauthority** [comment]
Interesting. Let's go bug hunting.

You're using the default configuration with no modifications whatsoever? So if I go to reproduce, I may follow these exact steps:

1. Bungeecord #1228 (latest)
2. Add my plugin
3. Start

Correct?

**Comment by simpleauthority** [comment]
Closing for now. There is a rewrite upcoming, so watch for updates on Spigot. Thank you for using SCB!
